Feature/data augmentation
retail-intelligence/yolov3-tf2 pull request #10
Opened 2021-03-31 18:02 UTC by R-R-Onzi

2021-04-01 17:12 UTC, tgcandido reviewed
Eu acho que podemos fazer uma 2.0 pra vetorizar esses calculos que ficam dentro dos `for`

2021-04-01 17:12 UTC, tgcandido commented on tools/tfrecord_test.py
> +            img = cv2.rectangle(
Isso não dá pra fazer vetorialmente?

2021-04-01 17:13 UTC, tgcandido commented on tools/tfrecord_test.py
> +            img = cv2.rectangle(
Tem outros exemplos mas não marquei todos

2021-04-05 19:56 UTC, OtherRandomUser requested changes

2021-04-05 19:56 UTC, OtherRandomUser commented on tools/tfrecord_test.py
> +            img = cv2.rectangle(
[Aparentemente não](https://docs.opencv.org/master/d6/d6e/group__imgproc__draw.html#ga07d2f74cadcf8e305e810ce8eed13bc9), nenhum dos overloads aceita um vetor.

2021-04-05 19:56 UTC, OtherRandomUser commented on yolov3_tf2/dataset.py
> +    transformations, aug_names = get_default_augmentation_pipeline()
Olhando essa função ela instancia a pipeline. Precisamos instanciar a pipeline toda vez que formos aumentar uma imagem? Isso não é ineficiente?

2021-04-05 19:56 UTC, OtherRandomUser commented on yolov3_tf2/dataset.py
> +            tf_examples = augment_image(annotation, images_dir, pascal_voc_dict, class_map)
essa função carrega a imagem do disco. Não é melhor passar a variável `raw_image` e as boxes pra ela copiar e aplicar as tranformações? Assim ela também não precisaria estar acoplada com o formato do dataset que estamos lendo.

2021-04-05 19:56 UTC, OtherRandomUser commented on yolov3_tf2/dataset.py
> +            tf_examples = augment_image(annotation, images_dir, pascal_voc_dict, class_map)
Tente sempre passar o mínimo de informação necessária pra uma função.

2021-04-05 19:56 UTC, OtherRandomUser commented on yolov3_tf2/dataset.py
> +def augment_image(annotation, images_dir, xml_data_dict, class_map):
essa função em geral faz bastante retrabalho. Evite retrabalho, ainda mais quando não é necessário. Carregar as imagens, ler as bounding boxes, tudo isso é trabalho feito antes de entrar na função que não precisa ser feito uma segunda vez.

2021-04-05 19:56 UTC, OtherRandomUser commented on yolov3_tf2/dataset.py
> +def augment_image(annotation, images_dir, xml_data_dict, class_map):
Nesse caso podemos passar a imagem, as bounding boxes, a pasta para salvar a imagem e o nome original do arquivo. Todas informações que tinhamos antes e não precisamos conseguir uma segunda vez.

2021-04-05 19:56 UTC, OtherRandomUser commented on yolov3_tf2/dataset.py
> +def get_bbox_dict(bbox_list, class_map) -> dict:
`class_map` não faz nada nessa função.

2021-04-05 19:56 UTC, OtherRandomUser commented on yolov3_tf2/dataset.py
> +def get_bounding_boxes(xml_data_dict: dict) -> list:
`get_` é um prefixo ruim, nesse caso eu usaria `parse_`

2021-04-05 19:56 UTC, OtherRandomUser commented on yolov3_tf2/dataset.py
> +def get_default_augmentation_pipeline() -> list:
`get_` é um prefixo ruim, nesse caso eu usaria `build_`

2021-04-06 14:42 UTC, R-R-Onzi commented on yolov3_tf2/dataset.py
> +            tf_examples = augment_image(annotation, images_dir, pascal_voc_dict, class_map)
74c2df9, 7773253. não é o formato mas sim a info contida no dict, diminui a quantidade de inputs e removi o carregamento dentro da função só carregamos uma vez agora.

2021-04-06 16:28 UTC, R-R-Onzi commented on yolov3_tf2/dataset.py
> +    transformations, aug_names = get_default_augmentation_pipeline()
7b590d9, sim, mudado.

2021-04-06 17:08 UTC, R-R-Onzi commented on yolov3_tf2/dataset.py
> +def get_bbox_dict(bbox_list, class_map) -> dict:
b8dc1c5  não só ali.

2021-04-06 17:29 UTC, R-R-Onzi commented on yolov3_tf2/dataset.py
> +def augment_image(annotation, images_dir, xml_data_dict, class_map):
ac6192b 
o metodo ficou com xml_data_dict, image, augmentation_list de parametro onde:
xml_data_dict: precisa para contruir o Example de cada aumentação, sem os dados n pode construir gerando mais trabalho depois para o método que recebe as aumentações.
image: precisa para aumentar
augmentation_list: aumentações a serem executadas com o nome delas para serem adicionadas ao Example de cada imagem.

2021-04-06 17:29 UTC, R-R-Onzi commented on yolov3_tf2/dataset.py
> +def get_bbox_dict(bbox_list, class_map) -> dict:
b8dc1c5

2021-04-06 17:33 UTC, R-R-Onzi commented on yolov3_tf2/dataset.py
> +def get_bounding_boxes(xml_data_dict: dict) -> list:
943b3d6

2021-04-06 17:35 UTC, R-R-Onzi commented on yolov3_tf2/dataset.py
> +def get_default_augmentation_pipeline() -> list:
b467fcc

2021-04-08 13:57 UTC, OtherRandomUser requested changes

2021-04-08 13:57 UTC, OtherRandomUser commented on yolov3_tf2/dataset.py
> +    augmentation_list = get_default_augmentation_pipeline()
Tu testou as alterações? por que essa função foi renomeada para `build_default_augmentation_pipeline`, `get_default_augmentation_pipeline` não existe mais

2021-04-08 13:57 UTC, OtherRandomUser commented on yolov3_tf2/dataset.py
> +        pascal_voc_dict['filename'] = annotation['filename']
isso não poderia ser feito em `parse_pascal_voc`?

2021-04-08 13:57 UTC, OtherRandomUser commented on yolov3_tf2/dataset.py
> +    return list(zip(transformations, aug_names))
Por que foi feita essa alteração se os lugares que usam essa função não foram alterados?

2021-04-08 17:23 UTC, R-R-Onzi commented on yolov3_tf2/dataset.py
> +    augmentation_list = get_default_augmentation_pipeline()
13888a7

2021-04-08 17:23 UTC, R-R-Onzi commented on yolov3_tf2/dataset.py
> +        pascal_voc_dict['filename'] = annotation['filename']
7046193

2021-04-08 17:30 UTC, R-R-Onzi commented on yolov3_tf2/dataset.py
> +    return list(zip(transformations, aug_names))
Como ele retornava 2 listas e puxei para fora da função que criava e usava a augmentation list (esse return), ao invés de passar duas listas é melhor passar uma lista de tuplas já que são usadas e só serão usadas em conjunto.

2021-04-08 17:31 UTC, R-R-Onzi commented on yolov3_tf2/dataset.py
> +    return list(zip(transformations, aug_names))
esse foi o motivo 7b590d9, achei melhor fazer desse jeito.

2021-04-08 18:51 UTC, OtherRandomUser commented on yolov3_tf2/dataset.py
> +    return list(zip(transformations, aug_names))
ok, tudo bem alterar o tipo do valor retornado, mas tu realmente não precisa alterar o cara que recebe isso? acho estranho

2021-04-09 12:27 UTC, OtherRandomUser approved these changes

2021-04-15 11:21 UTC, tgcandido approved these changes

2021-04-15 11:21 UTC, merged