Remove train_persondet
retail-intelligence/yolov3-tf2 pull request #2
Opened 2020-09-29 14:36 UTC by R-R-Onzi

2020-09-29 18:38 UTC, OtherRandomUser requested changes

2020-09-29 18:38 UTC, OtherRandomUser commented on setup.py
> +      packages=['yolov3_tf2', 'tools']
não inclua `tools` no pacote, passe ou copie as informações necessárias para `yolov3_tf2`. lembra de toda aquela discução sobre "ferramentas não são bibliotecas?" precisamos deixar isso claro

2020-09-30 12:34 UTC, R-R-Onzi commented on setup.py
> +      packages=['yolov3_tf2', 'tools']
23dd5ab

2020-09-30 17:55 UTC, OtherRandomUser approved these changes

2020-10-01 13:36 UTC, closed without merging